#!/usr/bin/env bash

alt_cyan="$(xrdb -query | grep '*alt_cyan:'| awk '{print $NF}')"

colorswitch () {
	sed -i -e "s/dwm.selbgcolor:.*/dwm.selbgcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.selbordercolor:.*/dwm.selbordercolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.titleselbgcolor:.*/dwm.titleselbgcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.titleselfloatcolor:.*/dwm.titleselfloatcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.tagsselbgcolor:.*/dwm.tagsselbgcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.tagsselfloatcolor:.*/dwm.tagsselfloatcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgbgcolor:.*/dwm.urgbgcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgbordercolor:.*/dwm.urgbordercolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgfloatcolor:.*/dwm.urgfloatcolor:$alt_cyan/" ~/.Xresources.d/dwm.xresources
	
	sed -i -e "s/\"Gruvbox-Material-Dark-Soft-.*/\"Gruvbox-Material-Dark-Soft-cyan\"/" ~/.xsettingsd
	sed -i -e "s/\"Gruvbox-Material-Dark-Soft-.*/\"Gruvbox-Material-Dark-Soft-cyan\"/" ~/.gtkrc-2.0
	sed -i -e "s/\Gruvbox-Material-Dark-Soft-.*/\Gruvbox-Material-Dark-Soft-cyan/" ~/.config/gtk-3.0/settings.ini
	
}
colorswitch 
