#!/usr/bin/env bash

yellow="$(xrdb -query | grep '*color3:'| awk '{print $NF}')"

colorswitch () {
	sed -i -e "s/dwm.selbgcolor:.*/dwm.selbgcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.selbordercolor:.*/dwm.selbordercolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.titleselbgcolor:.*/dwm.titleselbgcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.titleselfloatcolor:.*/dwm.titleselfloatcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.tagsselbgcolor:.*/dwm.tagsselbgcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.tagsselfloatcolor:.*/dwm.tagsselfloatcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgbgcolor:.*/dwm.urgbgcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgbordercolor:.*/dwm.urgbordercolor:$yellow/" ~/.Xresources.d/dwm.xresources
	sed -i -e "s/dwm.urgfloatcolor:.*/dwm.urgfloatcolor:$yellow/" ~/.Xresources.d/dwm.xresources
	
	sed -i -e "s/\"Gruvbox-Material-Dark-Soft-.*/\"Gruvbox-Material-Dark-Soft-yellow\"/" ~/.xsettingsd
	sed -i -e "s/\"Gruvbox-Material-Dark-Soft-.*/\"Gruvbox-Material-Dark-Soft-yellow\"/" ~/.gtkrc-2.0
	sed -i -e "s/\Gruvbox-Material-Dark-Soft-.*/\Gruvbox-Material-Dark-Soft-yellow/" ~/.config/gtk-3.0/settings.ini
}
colorswitch 
